---
# Credits

- name: Create unbound path
  ansible.builtin.file:
    path: /var/lib/unbound
    state: directory

- name: Download root hints
  get_url:
    url: https://www.internic.net/domain/named.root
    dest: /var/lib/unbound/root.hints

- name: Start and enable unbound service
  ansible.builtin.systemd:
    name: unbound
    state: started
    enabled: "yes"

- name: Unbound configuration
  ansible.builtin.template:
    src: unbound_pihole.j2
    dest: /etc/unbound/unbound.conf.d/pi-hole.conf
    owner: root
    group: root
    mode: "0644"

- name: Add pihole Group
  ansible.builtin.group:
    name: pihole
    state: present

- name: Add Pihole user
  ansible.builtin.user:
    name: pihole
    groups: pihole
    append: "yes"
    password: "{{ pihole_password }}"

- name: Create Pihole path
  ansible.builtin.file:
    path: /etc/pihole
    state: directory
    owner: pihole
    group: pihole
    mode: "0644"

- name: Pihole Config
  ansible.builtin.template:
    src: setup_vars.j2
    dest: /etc/pihole/setupVars.conf
    owner: pihole
    group: pihole
    mode: "0644"

- name: Clone Pihole Repo
  ansible.builtin.git:
    repo: https://github.com/pi-hole/pi-hole.git
    dest: "/home/{{ user_name }}/Pi-hole"

- name: Run Pihole Setup
  ansible.builtin.script: "\u0022/home/{{ user_name }}/Pi-hole/automated install/basic-install.sh\u0022"
  become: "true"

- name: Setup Allow and Block Lists
  ansible.builtin.shell:
    cmd: |
      sqlite3 '/etc/pihole/gravity.db' <<EOF
      DELETE FROM domainlist;
      INSERT INTO domainlist (id, type, domain, enabled, comment) VALUES {{ item }}
      EOF
  loop: "{{ allow_block_list }}"

- name: Setup Gravity Lists
  ansible.builtin.shell:
    cmd: |
      sqlite3 '/etc/pihole/gravity.db' <<EOF
      DELETE FROM adlist;
      INSERT INTO adlist (id, address, enabled, comment) VALUES {{ item }}
      EOF
  loop: "{{ adlist }}"

- name: Custom Domains
  ansible.builtin.lineinfile:
    path: /etc/pihole/custom.list
    line: "{{ item }}"
    create: "yes"
  loop: "{{ domains_list }}"
